version: '3'

services:
    postgres:
        container_name: Postgres-9.6
        
        image: postgres:9.6-alpine
        restart: unless-stopped

        environment:
            - POSTGRES_PASSWORD=password

        volumes:
            - /home/cgwire/postgresql/data:/var/lib/postgresql/data


    redis:
        container_name: Redis

        image: redis:alpine
        restart: unless-stopped


    
    cgwire:
        container_name: CGWire

        image: cgwire:latest
        restart: unless-stopped
        
        depends_on:
            - postgres
            - redis
        
        environment:
            - DB_HOST=postgres
            - DB_PORT=5432
            - DB_USERNAME=cgwire_db_user
            - DB_PASSWORD=password
            - DB_DATABASE=cgwire_db
            - SECRET_KEY=yourrandomsecretkey

            - KV_HOST=redis
            - KV_PORT=6379

            - PREVIEW_FOLDER=/opt/zou/previews

            - LC_ALL=C.UTF-8
            - LANG=C.UTF-8

        volumes:
            - /home/cgwire/previews:/opt/zou/previews

        ports:
            - '80:80'
               
